language: shell
dist: bionic
services: docker

jobs:
  include:
    - stage: "build"
      name: "php 7.3.x"
      script:
        - make build PHP=7.3
        - make push PHP=7.3
    - script:
      - make build PHP=7.4
      - docker tag dkimg/phpqa:7.4 dkimg/phpqa:latest
      - make push PHP=7.4
      - make push PHP=latest
      name: "php 7.4.x"
    - stage: "test"
      name: "php 7.3.x"
      script: make test PHP=7.3
    - script: make test PHP=7.4
      name: "php 7.4.x"
