os: linux
dist: bionic
language: shell
services: docker

jobs:
  include:
    # build and push images
    - stage: "build"
      script:
      - make PHP=7.4
      - make latest PHP=7.4
      name: "php 7.4.x"
    - script: make PHP=7.3
      name: "php 7.3.x"
    - script: make PHP=7.2
      name: "php 7.2.x"
    - script: make PHP=8.0
      name: "php 8.0.x"
    # pull and test images
    - stage: "test"
      script: make test PHP=7.4
      name: "php 7.4.x"
    - script: make test PHP=7.3
      name: "php 7.3.x"
    - script: make test PHP=7.2
      name: "php 7.2.x"
    - script: make test PHP=8.0
      name: "php 8.0.x"
